### ISSUE TITLE
Protect UI access to admins only

### ISSUE THREAD

**Issue by turgs** [bartoszkopinski/whenever-web#1]
I've added `mount Whenever::Web, at: '/whenever'` to `routes.rb`.

How do I limit access either using http basic authentication or some other means?

**Comment by bartoszkopinski** [comment]
@turgs If you're using devise you could use its [authenticated routes](https://github.com/plataformatec/devise/wiki/How-To:-Define-resource-actions-that-require-authentication-using-routes.rb).

Otherwise you can write a custom parent controller inheriting from Whenever::WebController:

``` ruby
class AdminController < Whenever::WebController
  http_basic_authenticate_with name: "user", password: "pass"
end
```

 and set it like this:

``` ruby
Whenever::Web.config.parent_controller = "AdminController"
```

**Comment by andre8888** [comment]
If you have admin flag, you can do the following in routes.rb:

authenticate :user, lambda { |u| u.admin? } do
    mount Whenever::Web, at: '/whenever'
  end
